version: '3.7'

services:
  web:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    environment:
      - SIDEKIQ_URL=redis://redis:6379
      - REDIS_URL=redis://redis:6379
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  sidekiq:
    build: .
    command: ["bundle", "exec", "sidekiq"]
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  mongodb_data:
  redis_data:
